iapiVersion: v1
kind: Service
metadata:
  name: empms-attendance-service
spec:
  selector:
    app: empms-attendance
  ports:
    - protocol: TCP
      port: 8081 
      targetPort: 8081 
  type: ClusterIP 

