apiVersion: apps/v1
kind: Deployment
metadata:
  name: empms-es-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-es
  template:
    metadata:
      labels:
        app: empms-es
    spec:
      containers:
        - name: empms-es
          image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3 # Elasticsearch image version
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx1024m"
            - name: ELASTIC_PASSWORD
              value: "elastic" # Define the password here
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              subPath: elasticsearch.yml
              readOnly: true
      volumes:
        - name: config-volume
          configMap:
            name: empms-es-config
