apiVersion: apps/v1
kind: Deployment
metadata:
  name: empms-es-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: empms-es
  template:
    metadata:
      labels:
        app: empms-es
    spec:
      containers:
        - name: empms-es
          image: sriniv7654/ot-elastic:1
          volumeMounts:
            - name: config-volume
              mountPath: /usr/share/elasticsearch/config/elasticsearch.yml
              readOnly: true
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: ES_JAVA_OPTS
              value: "-Xmx512m -Xms512m"
            - name: ELASTIC_PASSWORD
              value: elastic
      volumes:
        - name: config-volume
          hostPath:
            path: ./elasticsearch/elasticsearch.yml # Replace with the path to your elasticsearch.yml

