apiVersion: v1
kind: Service
metadata:
  name: empms-es-service
  namespace: default
spec:
  selector:
    app: empms-es
  ports:
    - protocol: TCP
      port: 9200
      targetPort: 9200
    - protocol: TCP
      port: 9300
      targetPort: 9300
