apiVersion: v1
kind: Service
metadata:
  name: empms-es-service
spec:
  selector:
    app: empms-es
  ports:
    - name: http
      protocol: TCP
      port: 9200
      targetPort: 9200
    - name: transport
      protocol: TCP
      port: 9300
      targetPort: 9300
